# 1.Print 'Hello HCIA'.

In [1]:
print('Hello HCIA')

Hello HCIA


# 2.Define two variables and calculate their sum.

In [2]:
a = 1
b = 2
print(a+b)

3


# 3.Define a list and replicate in three different ways.

In [30]:
l1 = ['1','2','3','4']
print(l1)
print(l1[:])
print(*l1)

['1', '2', '3', '4']
['1', '2', '3', '4']
1 2 3 4


# 4.Define two lists and merge them together.

In [3]:
l1 = ['1','2','3','4']
l2 = ['5','6','7','8']
mergedlist = l1 + l2
print(mergedlist)

['1', '2', '3', '4', '5', '6', '7', '8']


# 5. Get the last element of the list and print it.

In [5]:
l1 = ['1','2','3','4']
print(l1[-1:])

['4']


# 6.Define a tuple that contains only one element.

In [6]:
t = ('1')

# 7.Define a three-line long string.

In [22]:
str1 = "I'm learning Python.\nI refer to TechBeamers.com tutorials.\nIt is the most popular site for Python programmers."
print(len(str1))

110


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [10]:
t = ('1', '2', '3', '4')
for i in t:
    print(i)

1
2
3
4


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [8]:
def Mul(a,b):
    return(a*b)
print(Mul(8,6))

48


# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [11]:
import numpy as np
x = np.zeros((5,5))
print(x)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [12]:
x = np.zeros((4,6))
print(x)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [20]:
x = np.arange(15)
x.shape = (3,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [13]:
a = np.random.rand(3,2)
b = np.random.rand(2,3)
print(a.dot(b))

[[1.05405582 0.96405314 0.91417191]
 [0.31579929 0.29407866 0.29164794]
 [0.14691833 0.13315665 0.12330071]]
